# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bkJBiqnIDOvy3qLp0Ek6cN3dSiQkeOes
"""

import streamlit as st
import pickle
import numpy as np

# Load the trained model
with open('model.pkl', 'rb') as f:
    model = pickle.load(f)

# App title
st.title("Logistic Regression Predictor")

# Input fields (customize based on your model features)
feature1 = st.number_input("Enter Feature 1")
feature2 = st.number_input("Enter Feature 2")
# Add more features as needed

# Predict button
if st.button("Predict"):
    input_data = np.array([[feature1, feature2]])  # Adjust shape as needed
    prediction = model.predict(input_data)
    st.success(f"Prediction: {prediction[0]}")